github.com:
    users:
        morlibre581-del:
            oauth_token: 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
    git_protocol: https
    user: morlibre581-del
    oauth_token: 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
